### YamlMime:PythonClass
uid: azure.identity.AuthenticationRequiredError
name: AuthenticationRequiredError
fullName: azure.identity.AuthenticationRequiredError
module: azure.identity
inheritances:
- azure.identity._exceptions.CredentialUnavailableError
summary: 'Interactive authentication is required to acquire a token.


  This error is raised only by interactive user credentials configured not to automatically
  prompt for user

  interaction as needed. Its properties provide additional information that may be
  required to authenticate. The

  control_interactive_prompts sample demonstrates handling this error by calling a
  credential''s "authenticate"

  method.'
constructor:
  syntax: 'AuthenticationRequiredError(scopes: Iterable[str], message: str | None
    = None, claims: str | None = None, **kwargs: Any)'
  parameters:
  - name: scopes
    description: Scopes requested during the failed authentication
    isRequired: true
    types:
    - <xref:str>
  - name: message
    description: An error message explaining the reason for the exception.
    defaultValue: None
    types:
    - <xref:str>
  - name: claims
    description: Additional claims required in the next authentication.
    defaultValue: None
    types:
    - <xref:str>
methods:
- uid: azure.identity.AuthenticationRequiredError.add_note
  name: add_note
  summary: "Exception.add_note(note) \u2013\nadd a note to the exception"
  signature: add_note()
- uid: azure.identity.AuthenticationRequiredError.raise_with_traceback
  name: raise_with_traceback
  summary: 'Raise the exception with the existing traceback.


    Deprecated since version 1.22.0: This method is deprecated as we don''t support
    Python 2 anymore. Use raise/from instead.'
  signature: raise_with_traceback() -> None
- uid: azure.identity.AuthenticationRequiredError.with_traceback
  name: with_traceback
  summary: "Exception.with_traceback(tb) \u2013\nset self.__traceback__ to tb and\
    \ return self."
  signature: with_traceback()
attributes:
- uid: azure.identity.AuthenticationRequiredError.args
  name: args
- uid: azure.identity.AuthenticationRequiredError.claims
  name: claims
  summary: Additional claims required in the next authentication.
  return:
    types:
    - <xref:str>
    - <xref:None>
- uid: azure.identity.AuthenticationRequiredError.scopes
  name: scopes
  summary: Scopes requested during the failed authentication.
  return:
    types:
    - <xref:typing.Iterable>[<xref:str>]
- uid: azure.identity.AuthenticationRequiredError.continuation_token
  name: continuation_token
  signature: 'continuation_token: str | None'
- uid: azure.identity.AuthenticationRequiredError.error
  name: error
  signature: 'error: ODataV4Format | None'
- uid: azure.identity.AuthenticationRequiredError.exc_msg
  name: exc_msg
  signature: 'exc_msg: str'
- uid: azure.identity.AuthenticationRequiredError.exc_traceback
  name: exc_traceback
  signature: 'exc_traceback: TracebackType | None'
- uid: azure.identity.AuthenticationRequiredError.exc_type
  name: exc_type
  signature: 'exc_type: Type[Any] | None'
- uid: azure.identity.AuthenticationRequiredError.exc_value
  name: exc_value
  signature: 'exc_value: BaseException | None'
- uid: azure.identity.AuthenticationRequiredError.inner_exception
  name: inner_exception
  signature: 'inner_exception: BaseException | None'
- uid: azure.identity.AuthenticationRequiredError.message
  name: message
  signature: 'message: str'
- uid: azure.identity.AuthenticationRequiredError.model
  name: model
  signature: 'model: Any | None'
- uid: azure.identity.AuthenticationRequiredError.reason
  name: reason
  signature: 'reason: str | None'
- uid: azure.identity.AuthenticationRequiredError.response
  name: response
  signature: 'response: _HttpResponseCommonAPI | None'
- uid: azure.identity.AuthenticationRequiredError.status_code
  name: status_code
  signature: 'status_code: int | None'
